name: tinychat
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - pip:
    - transformers
    - datasets
    - accelerate
    - peft
